/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Joyce Ann
 */
public class Gradeslip extends javax.swing.JFrame {
  private String userEmail;
   



   
public Gradeslip(String email) {
    this.userEmail = email;
    initComponents();
    this.setLocationRelativeTo(null);
    loadGradesToSlip(); // Tawgon kini human ma-initialize ang components

}

  // Siguroha nga ang 'email' diri match sa 'lblEmail.setText(email)'


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lblSection = new javax.swing.JLabel();
        lblGradeLvl = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("GRADE SLIP");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 200, -1));

        jTable1.setBackground(new java.awt.Color(153, 153, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 330));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 80, -1));

        lblSection.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(lblSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 180, 30));

        lblGradeLvl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(lblGradeLvl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 160, 20));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 160, 20));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, 20));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                                                
    // Sugoon ang Java nga i-print ang tibuok jPanel (ang slip)
    printRecord(jPanel2); // Siguroha nga 'jPanel2' ang ngalan sa main container sa imong slip
}                                        

// Kini nga method maoy mo-handle sa pag-scale sa image para sakto sa papel
private void printRecord(javax.swing.JPanel panel) {
    java.awt.print.PrinterJob printerJob = java.awt.print.PrinterJob.getPrinterJob();
    printerJob.setJobName("Print Grade Slip");

    printerJob.setPrintable(new java.awt.print.Printable() {
        @Override
        public int print(java.awt.Graphics graphics, java.awt.print.PageFormat pageFormat, int pageIndex) throws java.awt.print.PrinterException {
            if (pageIndex > 0) {
                return java.awt.print.Printable.NO_SUCH_PAGE;
            }

            java.awt.Graphics2D g2 = (java.awt.Graphics2D) graphics;
            g2.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            
            // I-scale para mo-igo sa papel
            double scaleX = pageFormat.getImageableWidth() / panel.getWidth();
            g2.scale(scaleX, scaleX); 

            panel.printAll(g2); 
            return java.awt.print.Printable.PAGE_EXISTS;
        }
    });

    if (printerJob.printDialog()) {
        try {
            printerJob.print();
        } catch (java.awt.print.PrinterException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Print Error: " + e.getMessage());
        }
    }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Student_dashboard dash = new Student_dashboard(userEmail);
    
    // 2. I-pakita ang dashboard
    dash.setVisible(true);
    
    // 3. I-close kining ViewGrades frame
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gradeslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gradeslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gradeslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gradeslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
           if (UserSession.loggedInUser == null) {
    javax.swing.JOptionPane.showMessageDialog(null, "Required Login!");
    new login().setVisible(true);
  
           }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblGradeLvl;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSection;
    // End of variables declaration//GEN-END:variables

public void loadGradesToSlip() {
    // 1. I-setup ang Table Model
    String[] columnNames = {"Subject", "Q1", "Q2", "Q3", "Q4", "Average"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columnNames, 0);
    jTable1.setModel(model);

    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");

        // --- STEP A: KUHAON ANG GRADES (Parehas sa ViewGrades) ---
        String gradeSql = "SELECT subject, q1, q2, q3, q4, average FROM tbl_grades " +
                         "WHERE LOWER(student_name) LIKE (SELECT '%' || LOWER(fullname) || '%' FROM tbl_user WHERE email = ?)";
        java.sql.PreparedStatement pstmtGrade = conn.prepareStatement(gradeSql);
        pstmtGrade.setString(1, userEmail);
        java.sql.ResultSet rsGrade = pstmtGrade.executeQuery();

        while (rsGrade.next()) {
            model.addRow(new Object[]{
                rsGrade.getString("subject"),
                rsGrade.getString("q1"),
                rsGrade.getString("q2"),
                rsGrade.getString("q3"),
                rsGrade.getString("q4"),
                rsGrade.getString("average")
            });
        }

        // --- STEP B: KUHAON ANG NAME GIKAN SA tbl_user ---
        String userSql = "SELECT fullname FROM tbl_user WHERE email = ?";
        java.sql.PreparedStatement pstmtUser = conn.prepareStatement(userSql);
        pstmtUser.setString(1, userEmail);
        java.sql.ResultSet rsUser = pstmtUser.executeQuery();
        if (rsUser.next()) {
            lblName.setText("Name: " + rsUser.getString("fullname"));
        }

        // --- STEP C: KUHAON ANG SECTION UG GRADE LEVEL GIKAN SA tbl_transactions ---
        String transSql = "SELECT section, grade_level FROM tbl_transactions WHERE user_email = ? LIMIT 1";
        java.sql.PreparedStatement pstmtTrans = conn.prepareStatement(transSql);
        pstmtTrans.setString(1, userEmail);
        java.sql.ResultSet rsTrans = pstmtTrans.executeQuery();
        
        if (rsTrans.next()) {
            lblSection.setText("Section: " + rsTrans.getString("section"));
            lblGradeLvl.setText("Grade Level: " + rsTrans.getString("grade_level"));
        } else {
            // Kung wala pa siya'y gi-submit nga transaction
            lblSection.setText("Section: N/A");
            lblGradeLvl.setText("Grade Level: N/A");
        }

        // --- STEP D: I-SET ANG DATE KARON ---
        java.util.Date today = new java.util.Date();
        java.text.SimpleDateFormat formatter = new java.text.SimpleDateFormat("MMMM dd, yyyy");
        lblDate.setText("Date: " + formatter.format(today));

        conn.close();
    } catch (Exception e) {
        System.out.println("Gradeslip Error: " + e.getMessage());
    }
}
    }
    

   
