
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Joyce Ann
 */
public class ManageSubjects extends javax.swing.JFrame {
    private String adminEmail;

    /**
     * Creates new form ManageSubjects
     */
    public ManageSubjects() {
        initComponents();
        loadTable();
    }
    public ManageSubjects(String email) {
    this.adminEmail = email; // I-save ang email para sa Back button
    initComponents();
    loadTable(); // Siguroha nga mo-load ang table sa sugod
}
    
    public void loadTable() {
    DefaultTableModel model = (DefaultTableModel) tblMasterlist.getModel();
    
    // I-set ang mga Columns (Headers)
    model.setColumnCount(0); 
    model.addColumn("ID");
    model.addColumn("Grade Level");
    model.addColumn("Subject Name");
    model.addColumn("Teacher Name");
    
    // I-clear ang karaan nga data
    model.setRowCount(0); 
    
    try {
        Connection conn = DriverManager.getConnection("jdbc:sqlite:info.db");
        String sql = "SELECT * FROM tbl_subjects";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();
        
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("s_id"), 
                rs.getString("grade_level"), 
                rs.getString("subject_name"), 
                rs.getString("teacher_name")
            });
        }
        conn.close();
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbGrade = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSub = new javax.swing.JTextField();
        txtTeach = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMasterlist = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SUBJECT MANAGEMENT");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        cbGrade.setBackground(new java.awt.Color(153, 153, 255));
        cbGrade.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cbGrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GRADE", "GRADE 7", "GRADE 8", "GRADE 9", "GRADE 10", " " }));
        cbGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGradeActionPerformed(evt);
            }
        });
        jPanel1.add(cbGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Subject Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Teacher Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 30));

        txtSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubActionPerformed(evt);
            }
        });
        jPanel1.add(txtSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 220, 30));

        txtTeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeachActionPerformed(evt);
            }
        });
        jPanel1.add(txtTeach, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 220, 30));

        btnAdd.setBackground(new java.awt.Color(153, 153, 255));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdd.setText("ADD SUBJECT");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, 30));

        tblMasterlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblMasterlist);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 770, 200));

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, 30));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("VIEW LOGS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeachActionPerformed

    private void txtSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubActionPerformed

    private void cbGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGradeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
 
    String grade = cbGrade.getSelectedItem().toString();
    String subject = txtSub.getText();
    String teacher = txtTeach.getText();

    if(subject.trim().isEmpty() || teacher.trim().isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill the fields!");
        return;
    }

    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
        String sql = "INSERT INTO tbl_subjects (grade_level, subject_name, teacher_name) VALUES (?, ?, ?)";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, grade);
        pstmt.setString(2, subject);
        pstmt.setString(3, teacher);
        
        pstmt.executeUpdate();
        
       logAction("Added Subject: " + txtSub.getText());
        
        javax.swing.JOptionPane.showMessageDialog(this, "Success: Subject Added!");
        
        loadTable(); // I-refresh ang table
        txtSub.setText(""); // Limpyohan ang textfield
        txtTeach.setText("");
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }


    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
                                 
Admin_dashboard dash = new Admin_dashboard(this.adminEmail); 
    
    // I-pakita ang dashboard
    dash.setVisible(true);
    dash.setLocationRelativeTo(null);
    
    // Isira kining ManageSubjects window
    this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:ZZ
        // 1. Get the selected row index from the table
   int row = tblMasterlist.getSelectedRow();
    
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Palihog pili og subject sa table!");
        return;
    }

    // Kuhaon ang ID gikan sa Column 0 (s_id)
    String id = tblMasterlist.getValueAt(row, 0).toString();
    String subName = tblMasterlist.getValueAt(row, 2).toString();

    int confirm = JOptionPane.showConfirmDialog(this, "I-delete ang " + subName + "?", "Confirm", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            Connection conn = DriverManager.getConnection("jdbc:sqlite:info.db");
            // Siguroha nga tbl_subjects ang gamit
            String sql = "DELETE FROM tbl_subjects WHERE s_id = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, id);
            
            int deleted = pstmt.executeUpdate();
            
            if (deleted > 0) {
                logAction("Deleted Subject: " + subName); // Mo-save sa tbl_logs
                JOptionPane.showMessageDialog(this, "Successfully Deleted!");
                
                loadTable(); // Kini ang mo-refresh sa screen
            }
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ViewLogs logsFrame = new ViewLogs(); 
    logsFrame.setVisible(true);
    logsFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        if (UserSession.loggedInUser == null) {
    javax.swing.JOptionPane.showMessageDialog(null, "Required Login!");
    new login().setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox cbGrade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMasterlist;
    private javax.swing.JTextField txtSub;
    private javax.swing.JTextField txtTeach;
    // End of variables declaration//GEN-END:variables

    private void displayTransactions() {
       
    }
    public void logAction(String action) {
   
       try {
        Connection conn = DriverManager.getConnection("jdbc:sqlite:info.db");
        String sql = "INSERT INTO tbl_logs (user_email, action) VALUES (?, ?)";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        
        // Kung null ang email, ibutang nato "Admin_User"
        String email = (adminEmail == null || adminEmail.isEmpty()) ? "Admin_User" : adminEmail;
        
        pstmt.setString(1, email); 
        pstmt.setString(2, action);
        pstmt.executeUpdate();
        conn.close();
    } catch (Exception e) { 
        System.out.println("Log Error: " + e.getMessage()); 
    }
}

// Unsaon pagtawag sa Delete Button:
// logAction("Deleted Subject: " + subjectName);
}
