/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import static sun.net.www.MimeTable.loadTable;

/**
 *
 * @author Joyce Ann
 */
public class ManageGrades extends javax.swing.JFrame {
    private String adminEmail;

    /**
     * Creates new form ManageGrades
     */
    public ManageGrades() {
        initComponents();
        loadTable();
    }

    ManageGrades(String userEmail) {
        this.adminEmail = userEmail; // I-assign ang email gikan sa ReportFrame
    initComponents();
    loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtSection = new javax.swing.JTextField();
        txtSubject = new javax.swing.JTextField();
        txtQ1 = new javax.swing.JTextField();
        txtQ2 = new javax.swing.JTextField();
        txtQ3 = new javax.swing.JTextField();
        txtQ4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GRADES MANAGEMENT");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 340, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Student Email:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Section:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Subject:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(153, 153, 255));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GRADE & LEVEL", "Grade 7", "Grade 8", "Grade 9", "Grade 10", " " }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 650, 170));

        btnUpdate.setBackground(new java.awt.Color(153, 153, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 90, -1));

        btnDelete.setBackground(new java.awt.Color(153, 153, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 90, -1));

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 90, -1));

        btnClear.setBackground(new java.awt.Color(153, 153, 255));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 90, -1));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 120, 170, -1));
        jPanel1.add(txtSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 170, -1));
        jPanel1.add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 150, -1));
        jPanel1.add(txtQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 150, -1));
        jPanel1.add(txtQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 150, -1));
        jPanel1.add(txtQ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 150, -1));

        txtQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ4ActionPerformed(evt);
            }
        });
        jPanel1.add(txtQ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("1st Quarter:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("2nd Quarter:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("3rd Quarter:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("4th Quarter:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, 20));

        btnSave.setBackground(new java.awt.Color(153, 153, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Admin_dashboard dash = new Admin_dashboard(this.adminEmail); 
    
    // I-pakita ang dashboard
    dash.setVisible(true);
    dash.setLocationRelativeTo(null);
    
    // Isira kining ManageSubjects window
    this.dispose();
    
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtQ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ4ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    
    String sql = "INSERT INTO tbl_grades (student_name, grade_level, section, subject, q1, q2, q3, q4, average) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    
    try (java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
         java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
        // Siguroha nga ang txtName.getText() parehas sa Fullname sa tbl_user
        pstmt.setString(1, txtName.getText().trim()); 
        pstmt.setString(2, jComboBox1.getSelectedItem().toString());
        pstmt.setString(3, txtSection.getText());
        pstmt.setString(4, txtSubject.getText());
        pstmt.setDouble(5, Double.parseDouble(txtQ1.getText()));
        pstmt.setDouble(6, Double.parseDouble(txtQ2.getText()));
        pstmt.setDouble(7, Double.parseDouble(txtQ3.getText()));
        pstmt.setDouble(8, Double.parseDouble(txtQ4.getText()));
        
        // Calculate Average
        double avg = (Double.parseDouble(txtQ1.getText()) + Double.parseDouble(txtQ2.getText()) + 
                      Double.parseDouble(txtQ3.getText()) + Double.parseDouble(txtQ4.getText())) / 4;
        pstmt.setString(9, String.format("%.2f", avg));

        pstmt.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(null, "Grade Saved Successfully!");
        loadTable(); // I-refresh ang table sa admin
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
    int row = jTable1.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Palihog pili og row sa table.");
        return;
    }
    String id = jTable1.getValueAt(row, 0).toString(); // Kuhaon ang ID

    double g1 = Double.parseDouble(txtQ1.getText());
    double g2 = Double.parseDouble(txtQ2.getText());
    double g3 = Double.parseDouble(txtQ3.getText());
    double g4 = Double.parseDouble(txtQ4.getText());
    double avg = (g1 + g2 + g3 + g4) / 4.0;

    java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
    String sql = "UPDATE tbl_grades SET student_name=?, grade_level=?, section=?, subject=?, q1=?, q2=?, q3=?, q4=?, average=? WHERE grade_id=?";
    java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);

    pstmt.setString(1, txtName.getText());
    pstmt.setString(2, jComboBox1.getSelectedItem().toString());
    pstmt.setString(3, txtSection.getText());
    pstmt.setString(4, txtSubject.getText());
    pstmt.setDouble(5, g1);
    pstmt.setDouble(6, g2);
    pstmt.setDouble(7, g3);
    pstmt.setDouble(8, g4);
    pstmt.setString(9, String.format("%.2f", avg));
    pstmt.setString(10, id);

    pstmt.executeUpdate();
    javax.swing.JOptionPane.showMessageDialog(this, "Record Updated!");
    loadTable(); // Refresh table
    conn.close();
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Update Error: " + e.getMessage());
}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
if (row == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Pili una og row nga papason.");
    return;
}
String id = jTable1.getValueAt(row, 0).toString();
int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Sigurado ka nga papason kini?", "Delete Confirm", javax.swing.JOptionPane.YES_NO_OPTION);

if (confirm == javax.swing.JOptionPane.YES_OPTION) {
    try (java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db")) {
        String sql = "DELETE FROM tbl_grades WHERE grade_id=?";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, id);
        pstmt.executeUpdate();
        loadTable();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Delete Error: " + e.getMessage());
    }
}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    
    }//GEN-LAST:event_btnClearActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
    javax.swing.table.TableModel model = jTable1.getModel();
    
    // 2. I-set ang text sa matag box base sa data sa table
    // Ang index (0, 1, 2...) nag-agad sa pagkahan-ay sa imong columns sa loadTable()
    
    txtName.setText(model.getValueAt(i, 1).toString());      // Student Name
    jComboBox1.setSelectedItem(model.getValueAt(i, 2).toString()); // Level
    txtSection.setText(model.getValueAt(i, 3).toString());   // Section
    txtSubject.setText(model.getValueAt(i, 4).toString());   // Subject
    txtQ1.setText(model.getValueAt(i, 5).toString());        // Q1
    txtQ2.setText(model.getValueAt(i, 6).toString());        // Q2
    txtQ3.setText(model.getValueAt(i, 7).toString());        // Q3
    txtQ4.setText(model.getValueAt(i, 8).toString());        // Q4
    
    // Ang index 0 mao ang ID (tago), ang index 9 mao ang Average (automatic compute)

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQ1;
    private javax.swing.JTextField txtQ2;
    private javax.swing.JTextField txtQ3;
    private javax.swing.JTextField txtQ4;
    private javax.swing.JTextField txtSection;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables
private void loadTable() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    // I-set ang columns base sa imong tbl_grades sa info.db
    model.setColumnIdentifiers(new Object[]{"ID", "Student", "Level", "Section", "Subject", "Q1", "Q2", "Q3", "Q4", "Average"});

    try (java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db")) {
        java.sql.ResultSet rs = conn.createStatement().executeQuery("SELECT * FROM tbl_grades");
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("grade_id"),
                rs.getString("student_name"),
                rs.getString("grade_level"),
                rs.getString("section"),
                rs.getString("subject"),
                rs.getDouble("q1"),
                rs.getDouble("q2"),
                rs.getDouble("q3"),
                rs.getDouble("q4"),
                rs.getString("average")
            });
        }
    } catch (Exception e) {
        System.out.println("Error loading table: " + e.getMessage());
    }
}

    private void clearFields() {
  
    // Kini ang moforce nga mahimong blangko ang matag text box
    txtName.setText("");
    txtSection.setText("");
    txtSubject.setText("");
    txtQ1.setText("");
    txtQ2.setText("");
    txtQ3.setText("");
    txtQ4.setText("");
    
    // I-reset ang ComboBox sa pinakaunang item
    jComboBox1.setSelectedIndex(0);
    
    // I-focus ang cursor balik sa Name field para ready na sa bag-ong input
    txtName.requestFocus();
}  
}
