/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Joyce Ann
 */
public class Student_dashboard extends javax.swing.JFrame {
    private String userEmail;

    /**
     * Creates new form Student_dashboard
     */
    
    public Student_dashboard(String email) {
    this.userEmail = email; // I-set ang email
    initComponents();
    txtEmail.setText(userEmail); 
    
    
    txtEmail.setEditable(false); 
 
   displayTransactions();
    displayUserProfile();
}
    
    public Student_dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTeacher = new javax.swing.JTextField();
        txtSection = new javax.swing.JTextField();
        txtSubject = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbGrade = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnViewgrades = new javax.swing.JButton();
        btnSlip = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblProfile = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REQUEST GRADES");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 25, 130, 30));

        txtTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherActionPerformed(evt);
            }
        });
        jPanel2.add(txtTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 82, 200, 30));
        jPanel2.add(txtSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, 30));
        jPanel2.add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 82, 190, 30));

        txtEmail.setEditable(false);
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 190, 30));

        jLabel4.setText("Teacher's Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel5.setText("Section:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 116, -1, 30));

        jLabel12.setText("Email:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        cmbGrade.setBackground(new java.awt.Color(153, 153, 255));
        cmbGrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GRADE & LEVEL", "Grade 7", "Grade 8", "Grade 9", "Grade 10" }));
        jPanel2.add(cmbGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        btnSubmit.setBackground(new java.awt.Color(153, 153, 255));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 610, 170));

        btnViewgrades.setBackground(new java.awt.Color(153, 153, 255));
        btnViewgrades.setText("View My Grades");
        btnViewgrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewgradesActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewgrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        btnSlip.setBackground(new java.awt.Color(153, 153, 255));
        btnSlip.setText("View my Grades slip");
        btnSlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlipActionPerformed(evt);
            }
        });
        jPanel2.add(btnSlip, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        jLabel3.setText("Subject:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 110, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 640, 450));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student Dashboard");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 310, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 3, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("EDIT PROFILE");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 180, 30));

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 100));

        jPanel3.setLayout(new java.awt.BorderLayout());

        lblProfile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfile.setText("MY PROFILE");
        lblProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProfileMouseClicked(evt);
            }
        });
        jPanel3.add(lblProfile, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 170, 40));

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 170, 50));

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));
        jPanel5.setLayout(new java.awt.BorderLayout());

        lblLogout.setBackground(new java.awt.Color(204, 204, 204));
        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setText("LOGOUT");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        jPanel5.add(lblLogout, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 840, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeacherActionPerformed

    private void btnViewgradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewgradesActionPerformed
        // TODO add your handling code here:
        // 1. Paghimo og instance sa ViewGrades ug i-pasa ang email sa student
    ViewGrades view = new ViewGrades(userEmail);
    
    // 2. I-pakita ang ViewGrades frame
    view.setVisible(true);
    
    // 3. I-close (dispose) ang dashboard aron dili mag-double ang windows
    this.dispose();
    }//GEN-LAST:event_btnViewgradesActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
    String teacher = txtTeacher.getText().trim(); 
    String section = txtSection.getText().trim();
    String subject = txtSubject.getText().trim();
    String email = txtEmail.getText().trim();
    String gradeLevel = cmbGrade.getSelectedItem().toString();

    if(teacher.isEmpty() || section.isEmpty() || subject.isEmpty() || gradeLevel.equals("GRADE & LEVEL")){
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!");
        return;
    }

    try {
        java.sql.Connection conn = config.config.connectDB();
        // GI-REMOVE ANG 'status' SA SQL QUERY SA UBOS:
        String sql = "INSERT INTO tbl_transactions (user_email, grade_level, teacher_name, section, subject) VALUES (?, ?, ?, ?, ?)";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        
        pstmt.setString(1, email);
        pstmt.setString(2, gradeLevel);
        pstmt.setString(3, teacher);
        pstmt.setString(4, section);
        pstmt.setString(5, subject); // 5 na lang kabuok ang parameters (?)
        
        pstmt.executeUpdate();
        
        pstmt.close();
        conn.close(); 
        
        javax.swing.JOptionPane.showMessageDialog(this, "Saved Successfully!");
        
        displayTransactions(); // Refresh ang table
        
        // Limpyo sa fields
        txtTeacher.setText("");
        txtSection.setText("");
        txtSubject.setText("");
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }



    }//GEN-LAST:event_btnSubmitActionPerformed

    private void lblProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProfileMouseClicked
        // TODO add your handling code here:
          Studentprofile sp = new Studentprofile(userEmail); 
    sp.setVisible(true);
    this.dispose(); 

    }//GEN-LAST:event_lblProfileMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to logout?", "Logout Confirmation", 
            javax.swing.JOptionPane.YES_NO_OPTION);
    
    if(confirm == javax.swing.JOptionPane.YES_OPTION){
        // Replace 'Login' with the actual class name of your Login frame
        new login().setVisible(true); 
        this.dispose();
    }

    }//GEN-LAST:event_lblLogoutMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        // 1. Kuhaon ang index sa row nga gi-click
    int row = jTable1.getSelectedRow();
    
    // 2. Siguroha nga naay napili nga row (dili -1)
    if (row != -1) {
        // Base sa imong displayData() method, kini ang arrangement sa columns:
        // Index 0 = teacher_name, 1 = subject, 2 = section, 3 = grade_level, 4 = status
        
        String teacher = jTable1.getValueAt(row, 0).toString();
        String subject = jTable1.getValueAt(row, 1).toString();
        String section = jTable1.getValueAt(row, 2).toString();
        String gradeLvl = jTable1.getValueAt(row, 3).toString();
        
        
        // 3. I-set ang data ngadto sa imong mga text fields ug combobox
        txtTeacher.setText(teacher);
        txtSubject.setText(subject);
        txtSection.setText(section);
        cmbGrade.setSelectedItem(gradeLvl);
        
        // Siguroha nga visible ang email (txtEmail) kay gigamit man ni sa submission
        txtEmail.setText(userEmail); 
    }

        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlipActionPerformed
        // TODO add your handling code here:
        new Gradeslip(userEmail).setVisible(true);
    }//GEN-LAST:event_btnSlipActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
       EditProfile ep = new EditProfile(userEmail); 
    
    // 2. Ipakita ang window
    ep.setVisible(true);
    
    // 3. I-close ang dashboard (optional)
    this.dispose(); 

    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSlip;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnViewgrades;
    private javax.swing.JComboBox cmbGrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSection;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTeacher;
    // End of variables declaration//GEN-END:variables
private void displayUserProfile() {
        
     try {
        java.sql.Connection conn = config.config.connectDB();
        // Gi-apil ang profile_pic sa SELECT statement
        String sql = "SELECT fullname, profile_pic FROM tbl_user WHERE email = ?";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, userEmail); 
        java.sql.ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            // 1. I-set ang Title sa babaw (jLabel1)
            jLabel1.setText("REQUST GRADES"); 
            
            // 2. I-set ang Fullname sa student (jLabel7)
            jLabel7.setText(rs.getString("fullname")); 
            
            // 3. I-set ang Picture sa student (jLabel11)
            String path = rs.getString("profile_pic");
            if (path != null && !path.isEmpty()) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(path);
                
                // I-resize ang image base sa gidak-on sa jLabel11 sa imong design
                java.awt.Image img = icon.getImage().getScaledInstance(jLabel11.getWidth(), 
                    jLabel11.getHeight(), 
                    java.awt.Image.SCALE_SMOOTH
                );
                
                jLabel11.setIcon(new javax.swing.ImageIcon(img));
                jLabel11.setText(""); // Tangtangon ang text nga "jLabel11"
            }
        }
        rs.close();
        pstmt.close();
        conn.close();
    } catch (Exception e) {
        System.out.println("Error loading profile: " + e.getMessage());
    }

}

private void displayTransactions() {
    // 1. Gikuha ang "Status" sa column headers
    String[] columnNames = {"ID", "Email", "Grade Level", "Teacher", "Section", "Subject"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columnNames, 0);
    jTable1.setModel(model); 

    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
        
        // 2. Gikuha ang 'status' sa SQL SELECT query
        String sql = "SELECT t_id, user_email, grade_level, teacher_name, section, subject FROM tbl_transactions WHERE user_email = ?";
        
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, userEmail); 
        java.sql.ResultSet rs = pstmt.executeQuery();

        while(rs.next()){
            // 3. Gikuha ang rs.getString("status") aron dili mo-error ang pag-add sa row
            model.addRow(new Object[]{
                rs.getInt("t_id"),
                rs.getString("user_email"),
                rs.getString("grade_level"),
                rs.getString("teacher_name"),
                rs.getString("section"),
                rs.getString("subject")
            });
        }
        conn.close();
    } catch (Exception e) {
        System.out.println("Error loading transactions: " + e.getMessage());
    }
}
}